MODEL:
  INPUT_SIZE: 224
TRAIN:
  EPOCH: 700
  BURN_IN: 100
  BATCH_SIZE: 8
  LEARNING_RATE: 1.0e-4
  NUM_LAYERS: 16
  PRETRAINED: True
  DEVICE: "cuda"
  DATA_DIR: "/content/mvtec-ad/screw"
  SAVE_DIR: "/content/drive/MyDrive/Anomaly-Detection/DFR"
  RESUME_TRAIN: False
  CHECKPOINT_PATH: "/content/drive/MyDrive/Anomaly-Detection/DFR/last.pt"
